### ISSUE TITLE
cts:min, cts:max accept cts:point also

### ISSUE THREAD

**Issue by innovimax** [joemfb/group-by#2]
Do you support any processing with cts:point ?

**Comment by joemfb** [comment]
Well, it was a long time coming ... ;)

This library, the JSON interface, the REST interface, and the dependency [cts-extensions](https://github.com/joemfb/cts-extensions) all have support for geospatial lexicon references. Additionally, they all have support for the new ML 8 JSON property and geospatial lexicon references. That's implemented in a backward-compatible way, so these modules all work with ML 7 as well.

Any easy way to try it out is to install this [query browser](https://github.com/joemfb/analytics-query-browser).

Thanks!
